sass:
  sass_dir: _scss
  style: compressed

markdown: kramdown
theme: jekyll-kde-theme

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  changelogs:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

