source "https://rubygems.org"
ruby RUBY_VERSION

gem "jekyll", "3.8"
gem "kde-jekyll-theme", path: '../kde-jekyll-theme'

# If you have any plugins, put them here!
# group :jekyll_plugins do
#   gem "jekyll-github-metadata", "~> 1.0"
# end
